---
title: "Practice"
author: "Richard Liu"
date: "9/14/2021"
output: html_document
---
```{r packages, message=FALSE}
library(tidyverse)
library( phyloseq)
```

```{r load-data, message=FALSE}
GlobalPatterns = "~/Desktop/Lab/GlobalPatterns.RData"
```

```{r first-plot}
data(GlobalPatterns)
plot_richness(GlobalPatterns, x="SampleType", measures=c("Observed", "Chao1", "Shannon"))
```

```{r second plot}
p = (plot_richness(GlobalPatterns, x = "SampleType", measures = c("ACE", "Shannon", "Simpson")))
p
```

```{r second-geomplot}
p+geom_boxplot(data = p$data, aes(x = SampleType, y = value), alpha = 0.2, fill = "steelblue")
```

```{r tree}
GP_chlam = subset_taxa(GlobalPatterns, Phylum == "Chlamydiae")
plot_tree(GP_chlam, color = "SampleType", shape = "Family", label.tips = "Genus", 
    size = "abundance", plot.margin = 0.5, ladderize = TRUE)
```

```{r heatmap}
GP_bac <- subset_taxa(GlobalPatterns, Kingdom == "Bacteria")
GP_bac <- prune_taxa(names(sort(taxa_sums(GP_bac),TRUE)[1:500]), GP_bac)
plot_heatmap(GP_bac, sample.label = "SampleType")
```


